# Generated by Django 2.1 on 2019-01-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
