# Generated by Django 2.1 on 2019-01-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190125_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='time',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
