# Generated by Django 2.1 on 2019-01-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_parkinglot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
